name: codecov
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        
      - name: pester
        run: |
          Set-PSRepository psgallery -InstallationPolicy trusted
          Install-Module -Name Pester -RequiredVersion 5.0.4 -Force;
          $paths = @('.\CloudiQ\functions\*.ps1','.\CloudiQ\functions\organization\*.ps1','.\CloudiQ\functions\subscription\*.ps1')
          Invoke-Pester -Path "tests" -CodeCoverage $paths -CodeCoverageOutputFileFormat "JaCoCo";
        shell: pwsh
      
      - name: Codecov
        uses: codecov/codecov-action@v1.0.13
        with:
          name: civoShell
          token: ${{ secrets.CODECOV }}
          file: coverage.xml
